# Generated by Django 4.1.7 on 2023-07-19 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_taskdelivery_id_barang_taskdelivery_id_barang'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskdelivery',
            name='id_barang',
        ),
        migrations.AddField(
            model_name='admin',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='taskdelivery',
            name='barang',
            field=models.ManyToManyField(to='app.barang'),
        ),
    ]
