# Generated by Django 4.1.7 on 2023-07-19 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_taskdelivery_id_barang_admin_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='is_staff',
        ),
    ]
